#!/usr/bin/perl

# in case we get executed (not sourced) as a shell program
eval 'exec perl -S $0 ${1+"@"}'
    if $running_under_some_shell;

BEGIN {
    use strict;
    use warnings;
    my $here = $0; $here =~ s{/[^/]*$}{};
    if ($here =~ s{^\.}{}) {
	chomp(my $cwd = `pwd`);
	$here = "/$here" if $here;
	$here = "$cwd$here";
    }
    unshift @INC, "$here/lib" unless $here =~ m{^/usr/bin};
}

use Gtk2;

Gtk2::Rc->set_default_files("$ENV{HOME}/.gtkrc-2.0.xde");

use Getopt::Long;
use Encode;
use I18N::Langinfo qw(langinfo CODESET);
use POSIX qw(locale_h);
use XDE::Desktop;
use strict;
use warnings;

my %OVERRIDES = ();
my $here = $0; $here =~ s{/[^/]*$}{};
if ($here =~ s{^\.}{}) {
    chomp(my $cwd = `pwd`);
    $here = "/$here" if $here;
    $here = "$cwd$here";
}
unless ($here =~ m{^/usr/bin}) {
    %OVERRIDES = (
	HERE               => "$here",
	XDG_CONFIG_PREPEND => "$here/xdg/xde:$here/xdg",
	XDG_DATA_PREPEND   => "$here/share/xde:$here/share",
	XDG_ICON_APPEND    => "$here/share/icons:$here/share/pixmaps",
    );
    my %path = (map{$_=>1}split(/:/,$ENV{PATH}));
    $ENV{PATH} = "$here:$ENV{PATH}" unless exists $path{$here};
}

my $program = $0; $program =~ s{^.*/}{};

my %ops = (
    help	=> '',
    verbose	=> '',
    prompt	=> '',
    banner      => '',
    noask	=> '',
    charset	=> langinfo(CODESET),
    language	=> setlocale(LC_MESSAGES),
    setdflt     => '',
    default	=> '',
    current	=> '',
    choice	=> '',
    vendor	=> '',
    monitor	=> 1,
    grab	=> 1,
    theme	=> '',
    id		=> '',
    setroot	=> 1,
);

my $xde = XDE::Desktop->new(%OVERRIDES,ops=>\%ops);
$xde->getenv;

my $syntax = GetOptions(
    'help|h'	    => \$ops{help},
    'verbose|v'	    => \$ops{verbose},
    'monitor!'	    => \$ops{monitor},
    'setroot|s'	    => \$ops{setroot},
    'grab|g'	    => \$ops{grab},
    'n'		    => sub{ $ops{monitor} = 0 },
    'id=s'	    => \$ops{id},
);

$xde->default; # reset defaults

$xde->init;
$xde->read_primary_data;
$xde->update_desktop;
$xde->main;
$xde->term;

exit(0);

sub show_usage {
    return <<USAGE_EOF;

USAGE:
    xde-desktop
USAGE_EOF
}

1;

__END__

=head1 NAME

xde-desktop - a desktop environment for XDE

=head1 SYNOPSIS

B<xde-desktop> [I<OPTIONS>]

=head1 DESCRIPTION

Provides a desktop environment for window managers that do not support
one and provides a more consistent and rich experience for those that
do.

Like most desktop environments (typically file managers run in a desktop
mode), B<xde-desktop> provides clickable icons on the desktop.
Following the XDG specifications, it places items from the user's
F<~/Desktop> directory on the background.
Unlike most file managers run in a desktop mode, B<xde-desktop> does not
involve itself with setting the background image.  That is the domain of
L<xde-setbg(1p)>.  In general, B<xde-desktop> cooperates with any
background setting utilities using the root X window property,
C<_XROOTPMAP_ID>.

B<xde-desktop> can be run stand-alone and does not required the reset of
the I<XDE> suite to operate properly.  It is written in L<perl(1)> and
relies on L<Gtk2(3pm)>, L<X11::Protocol(3pm)>, L<Linux::Inotify2(3pm)>
and L<Gnome2::VFS(3pm)>.

=head1 OPTIONS

B<xde-desktop> provides a number of options.  None are required for full
and proper operation.  They are, however, as follows:

=over

=item B<--help>, B<-h>

Prints usage information and defaults to standard output and exits.

=item B<--verbose>, B<-v>

Prints copious debugging information to standard error while operating.

=item B<--editor>, B<-e>

When specified (or when the program is called as F<xde-desktop-edit>),
launch the desktop configuration settings editor.  This is the default
when called as F<xde-desktop-edit>.

=item B<--restart>, B<-r>

When specified, ask the currently running B<xde-desktop> instance to
restart and exit.

=item B<--quit>, B<-q>

When specified, ask the currently running B<xde-desktop> instance to
quit and exit.

=item B<--filename>, B<-f> I<FILENAME>

Specify the file to use as the configuration file instead of the
default.  The default is F<XDG_CONFIG_HOME/xde/desktop.ini>.  This
option does not recognize C<-> as standard input: use F</dev/stdin>
instead.

=item B<--display>, B<-d> I<DISPLAY>

Specifies the display to use.  This is not normally necessary as the
display is obtained from the C<DISPLAY> environment variable when this
option is not specified.

=item B<--desktop>, B<-e> I<DESKTOP>

Specify the desktop environment (DE) to use, I<DESKTOP>, e.g.
C<FLUXBOX>, C<BLACKBOX>, C<ICEWM>, etc.  The default value when not
specified is C<FLUXBOX>.
This option may also be specified using the C<XDG_CURRENT_DESKTOP>
environment or B<FBXDG_DE> environment variable described below.

=back

=head1 ENVIRONMENT VARIABLES

As an XDG compatible application, B<xde-desktop> considers the following
environment variables when calculating the location of the user's
configuration file and the default configuration files:

=over

=item C<XDG_CONFIG_HOME>

When unspecified, defaults to F<$HOME/.config> in accordance with XDG
specifications.  B<xde-desktop> looks for user configuration files in
F<$XDG_CONFIG_HOME/xde/desktop.ini>.

=item C<XDG_CONFIG_DIRS>

When unspecified, defaults to F</etc/xdg> in accordance with XDG
specifications.  XDE will prepend the F</etc/xdg/xde> director to this
path if it does not already exist in the path.  B<xde-desktop> looks for
system configuration files in F<@XDG_CONFIG_DIRS/xde/desktop.ini>.

=back

=head1 SIGNALS

B<xde-desktop> intercepts and acts upon the following signals:

=over

=item $SIG{HUP}

When B<xde-desktop> receives a C<$SIG{HUP}> signal, it rereads the
configuration file.

=item $SIG{TERM}

When B<xde-desktop> receives a C<$SIG{TERM}> signal, it writes its
configuration file if possible before exiting gracefully.

=back

=head1 CONFIGURATION FILE

When B<xde-desktop> starts, it reads the configuration file located in
F<$XDG_CONFIG_HOME/xde/desktop.ini> unless the configuration file was
overridden with options on the command line.  If the configuration file
does not exist, it copies the first file that it finds in
F<@XDG_CONFIG_DIRS/xde/desktop.ini>.  When no configuration file is
found at all, it uses default settings and will write the current
(default) configuration to the configuration file.

All configuration keys can be manipulated using the GUI and it is
unnecessary to hand-edit the configuration file.  Format of the
configuration file is subject to change without notice, there should be
no need to rely upon it anyway.

=head1 BEHAVIOUR

When B<xde-desktop> starts, it creates a window that is the size of the
desktop and places it below all other windows.  To the user, it appears
as though it is the root window.  Scroll wheel motions (without
modifiers) are normally passed to the window manager by passing events
to the root window.  For some window managers, scroll events are
intercepted and used to change the desktop. See L</WINDOW MANAGERS> for
which.

=head1 WINDOW MANAGERS

B<xde-desktop> supports all EWMH 1.5/WMH/ICCCM 2.0 compliant window
managers.  It even supports some plain ICCCM/Motif WMH compliant window
managers that do not support EWMH or WMH (such as L<twm(1)> and
L<mwm(1)>).  Tested window managers and the idiosyncrasies handled for
them are as follows:

=over

=item L<fluxbox(1)>

=item L<blackbox(1)>

=item L<openbox(1)>

L<openbox(1)> has a strange idea for changing desktops using scroll
events.  Scroll events only change desktops within a row of the desktop
layout.  B<xde-desktop> intercepts scroll events on the desktop and
makes this consistent with other window managers.

=item L<icewm(1)>

L<icewm(1)> has no idea about changing desktops with scroll events
unless specifically specified in configuration files.  B<xde-desktop>
intercepts scroll events on the desktop and makes this consistent with
other window managers.

=item L<jwm(1)>

L<jwm(1)> does not consider its own panel when specifying
C<_NET_WORKAREA>.  I don't know whether I missed some "do not cover
panel" configuration item or whether it is a bug in L<jwm(1)>.
Nevertheless, B<xde-desktop> works around this problem by reducing the
height of the work area by 1/2 of an icon height.

L<jwm(1)> reverses the response to scroll events on the desktop.  It
moves left when others move right and vise versa.  B<xde-desktop>
intercepts scroll events on the desktop for this window manager and
makes this consistent with other window managers.

=item L<pekwm(1)>

L<pekwm(1)> has a strange idea for changing desktops using scroll
events.  Scroll events only change desktops within a row of the desktop
layout.  B<xde-desktop> intercepts scroll events on the desktop and
makes this consistent with other window managers.

=item L<wmaker(1)>

=item L<fvwm(1)>

=item L<afterstep(1)>

=item L<metacity(1)>

=item L<twm(1)>

=item L<mwm(1)>

=back

=head1 HISTORY

I wrote B<xde-desktop> primarily because L<pcmanfm(1)> from the I<LXDE>
suite would not allow changing desktops with the scroll wheel for any
window manager other than L<openbox(1)>.  I started using L<idesk(1)>;
however, it leaks memory when the background pixmap changes and
eventually turns into a runaway.  So, I wrote B<xde-desktop>.  Most of
the ideas and techniques were taken from the L<rox(1)> desktop: it is
too bad that L<rox(1)> is not XDG compliant.

=head1 AUTHOR

Brian Bidulock <bidulock@cpan.org>

=head1 SEE ALSO

=cut

# vim: set sw=4 tw=72:
